#!/usr/bin/env python3

import requests
import json
from faker import Faker


APIHOST = "http://library.demo.local"
LOGIN = "cisco"
PASSWORD = "Cisco123!"

def getAuthToken():
    authCreds = (LOGIN, PASSWORD)
    r = requests.post(
        f"{APIHOST}/api/v1/loginViaBasic", 
        auth = authCreds
    )
    if r.status_code == 200:
        return r.json()["token"]
    else:
        raise Exception(f"Status code {r.status_code} and text {r.text}, while trying to Auth.")

def addBook(book, apiKey):
    r = requests.post(
        f"{APIHOST}/api/v1/books", 
        headers = {
            "Content-type": "application/json",
            "X-API-Key": apiKey
            },
        data = json.dumps(book)
    )
    if r.status_code == 200:
        print(f"Book {book} added.")
    else:
        raise Exception(f"Error code {r.status_code} and text {r.text}, while trying to add book {book}.")

def addBookput(up, apiKey):
    r = requests.put(
        f"{APIHOST}/api/v1/books/{up['id']}", 
        headers = {
            "Content-type": "application/json",
            "X-API-Key": apiKey
            },
        data = json.dumps(up)
    )
    if r.status_code == 200:
        print(f"Book {up} update.")
    else:
        raise Exception(f"Error code {r.status_code} and text {r.text}, while trying to add book {up}.")

def addBookdel(delet, apiKey):
    r = requests.delete(
        f"{APIHOST}/api/v1/books/{delet['id']}", 
        headers = {
            "Content-type": "application/json",
            "X-API-Key": apiKey
            },
        data = json.dumps(delet)
    )
    if r.status_code == 200:
        print(f"Book {delet} delete.")
    else:
        raise Exception(f"Error code {r.status_code} and text {r.text}, while trying to add book {delet}.")
# Get the Auth Token Key
apiKey = getAuthToken()

# Using the faker module, generate random "fake" books
fake = Faker()
for i in range(4, 105):
    fakeTitle = fake.catch_phrase()
    fakeAuthor = fake.name()
    fakeISBN = fake.isbn13()
    book = {"id":i, "title": fakeTitle, "author": fakeAuthor, "isbn": fakeISBN}
    addBook(book, apiKey)
    # add the new random "fake" book using the API

#update do livro id 37
up = {"id":30, "title": 'teste', "author": 'teste', "isbn": fake.isbn13()}
addBookput(up, apiKey)

#apagando o livro de id 38
delet = {"id":31}
addBookdel(delet, apiKey)


